### ISSUE TITLE
[BUG] other.leapMonth = getLunarMonth();

### ISSUE THREAD

**Issue by iTanken** [heqiao2010/LunarCalendar#13]
https://github.com/heqiao2010/LunarCalendar/blob/becfcd9c819da39e5b7cca6a037a49f58a6a2c5c/lunar/src/main/java/com/github/heqiao2010/lunar/LunarCalendar.java#L657

Should be：

```java
other.lunarMonth = getLunarMonth();
```

**Comment by heqiao2010** [comment]
Thanks~
