### ISSUE TITLE
add(field, amount) 方法的疑问

### ISSUE THREAD

**Issue by du00cs** [heqiao2010/LunarCalendar#17]
add(年/月/日, 数量) 的方法只有在日上是正确的，在月（农历月？）年（农历年）上是不正确的。比如

农历二〇一三年三月初一

加一年是 农历 二〇一四年三月十一

减一年是 农历 二〇一二年三月二十

我这边想做一个按按农历加减的，不知道 add 方法是否本意是与我描述的一样。

**Comment by heqiao2010** [comment]
这里的add是继承自父类的，那个filed取值是指公历。
