### ISSUE TITLE
调用 LunarCalendar<init>IIIZZ; 发生NullPointerException

### ISSUE THREAD

**Issue by ZYFDroid** [heqiao2010/LunarCalendar#2]
构造器 (int year, int month, int day, boolean isLunar, boolean isLeapMonth)
在调用getSolar之前未初始化solar字段，导致空指针异常。应该在这个方法第一行加一个:
solar =new GregorianCalendar();

**Comment by ZYFDroid** [comment]
![screenshot_20180815-220121](https://user-images.githubusercontent.com/39429452/44152008-c9401188-a0d6-11e8-80f6-85073f9ef0dc.png)

**Comment by heqiao2010** [comment]
已修正
