### ISSUE TITLE
农历转公历方法闰月如何传值

### ISSUE THREAD

**Issue by duhui1230** [heqiao2010/LunarCalendar#6]
任意选择某一年
如农历2019.08.15
这里要额外传是否闰月，这个如何获取呢？

Calendar today = LunarCalendar.lunar2Solar(lunar.getLyear(), lunar.getLmonth(), lunar.getLdate(), lunar.isLeapMonth());

**Comment by heqiao2010** [comment]
2019年没有闰月,如果有闰月的话,月份前面会带一个"闰"字,比如:

2020年闰四月初二 和 2020年四月初二 是两个不同的日期.
